version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to ECR
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 850610451136.dkr.ecr.eu-north-1.amazonaws.com

  build:
    commands:
      - echo Build started
      - docker build -t my-app .
      - docker tag my-app:latest 850610451136.dkr.ecr.eu-north-1.amazonaws.com/my-app

  post_build:
    commands:
      - echo Pushing image
      - docker push 850610451136.dkr.ecr.eu-north-1.amazonaws.com/my-app
